# NumPy : Mise en pratique et manipulation avancée

Contexte

Un supermarché souhaite extraire des informations des données dont elle dispose. Ces données sont stockées dans différents arrays sur lesquels vous allez travailler pour extraire des informations de base utiles à l'entreprise comme le chiffre d'affaires réalisé par l'entreprise.

Vous disposez de 3 tableaux items, quantities et unit_price renseignant respectivement le nom des produits vendus, les quantités vendues et les prix de vente à l'unité. Ils ont chacun 25 éléments et les prix donnés sont en euro.



In [1]:
# Exécuter la cellule suivante.
import numpy as np

items = np.array(["headphones","glass","pencils","flowers","bread","speakers","chocolate",
                  "fridge","bowl","shirt","vegetables","jeans","monitor","piano","crisps","clamp",
                  "air fresher","Toothbrush","knife","hanger","glue","bucket","vase","books",
                  "football shirt"])

quantities = np.array([210, 800, 550, 200, 820, 415, 500, 24, 230, 520, 12, 550, 32,
                       10, 950, 500, 757, 642, 873,  71, 456, 230, 115, 854, 63])

unit_price = np.array([55, 10, 5, 20, 1, 70, 15, 500, 20, 10, 15, 25, 120, 500, 12, 18, 10,
                      3, 10, 12, 5, 20, 25, 14, 70])
items, quantities, unit_price

(array(['headphones', 'glass', 'pencils', 'flowers', 'bread', 'speakers',
        'chocolate', 'fridge', 'bowl', 'shirt', 'vegetables', 'jeans',
        'monitor', 'piano', 'crisps', 'clamp', 'air fresher', 'Toothbrush',
        'knife', 'hanger', 'glue', 'bucket', 'vase', 'books',
        'football shirt'], dtype='<U14'),
 array([210, 800, 550, 200, 820, 415, 500,  24, 230, 520,  12, 550,  32,
         10, 950, 500, 757, 642, 873,  71, 456, 230, 115, 854,  63]),
 array([ 55,  10,   5,  20,   1,  70,  15, 500,  20,  10,  15,  25, 120,
        500,  12,  18,  10,   3,  10,  12,   5,  20,  25,  14,  70]))

In [2]:
# (a) Multiplier unit_price avec quantities pour obtenir pour chaque produit le chiffre d’affaires réalisé.
# (b) Stocker le résultat dans une variable nommée ca_per_product

ca_per_product = unit_price * quantities
print(ca_per_product)

[11550  8000  2750  4000   820 29050  7500 12000  4600  5200   180 13750
  3840  5000 11400  9000  7570  1926  8730   852  2280  4600  2875 11956
  4410]


In [3]:
# (c) Déterminer le produit sur lequel le magasin fait le plus gros chiffre d'affaires.

print(items[ca_per_product.argmax()])

speakers


In [4]:
# (d) Déterminer le chiffre d'affaires réalisé par le magasin.

print(ca_per_product.sum())

173839


In [5]:
# (e) Déterminer la quantité moyenne de produits vendus.

print(quantities.mean())

415.36


In [6]:
# (f) Déterminer le produit qui a été le moins vendu par le magasin. 

print(items[quantities.argmin()])


piano


In [7]:
# (g) Déterminer le produit qui a été le plus vendu par le magasin.

print(items[quantities.argmax()])

crisps


In [8]:
# (h) Déterminer la quantité totale de produits vendus par le magasin.

print(quantities.sum())  

10384


In [9]:
# (i) Construire un tableau tab composé de deux colonnes contenant pour la première les quantités vendues et 
# la deuxième le prix de vente à l'unité.
tab = np.array([quantities, unit_price]).T
print(tab)

[[210  55]
 [800  10]
 [550   5]
 [200  20]
 [820   1]
 [415  70]
 [500  15]
 [ 24 500]
 [230  20]
 [520  10]
 [ 12  15]
 [550  25]
 [ 32 120]
 [ 10 500]
 [950  12]
 [500  18]
 [757  10]
 [642   3]
 [873  10]
 [ 71  12]
 [456   5]
 [230  20]
 [115  25]
 [854  14]
 [ 63  70]]


In [10]:
# (j) Ne garder dans tab que les prix supérieurs ou égaux à 10 euros et inférieurs ou égaux à 50 euros.
tab = tab[(tab[:,1] >= 10) & (tab[:,1] <= 50)]
print(tab)

[[800  10]
 [200  20]
 [500  15]
 [230  20]
 [520  10]
 [ 12  15]
 [550  25]
 [950  12]
 [500  18]
 [757  10]
 [873  10]
 [ 71  12]
 [230  20]
 [115  25]
 [854  14]]


In [11]:
# (k) Déterminer le chiffre d'affaires obtenu sur les produits ayant un prix de vente compris entre 10 et 50 euros.
# Stocker le résultat dans une variable ca.

ca = (tab[:,0]*tab[:,1]).sum()
print(round(ca/ca_per_product.sum(), 2)*100,"% du chiffre d'affaire est réalisé par ces produits")

57.99999999999999 % du chiffre d'affaire est réalisé par ces produits


In [12]:
# (l) Diviser le résultat par le chiffre d'affaires total que vous avez du calculer précédemment.

TB = ca/ca_per_product.sum()

print(round(TB, 2)*100,"% du chiffre d'affaire est réalisé par ces produits")

57.99999999999999 % du chiffre d'affaire est réalisé par ces produits


In [13]:
# (m) Faire le même raisonnement sur les produits ayant des prix strictement supérieurs à 50 et inférieurs ou égaux à 500 euros.

tab2 = np.array([quantities, unit_price]).T
tab2 = tab2[(tab2[:,1] > 50) & (tab2[:,1] <= 500)]

ca2 = (tab2[:,0]*tab2[:,1]).sum()

print(round(ca2/ca_per_product.sum(), 2)*100,"% du chiffre d'affaire est réalisé par ces produits")

38.0 % du chiffre d'affaire est réalisé par ces produits


In [15]:
# (n) Créer une fonction value_counts prenant un array comme paramètre 
# renvoyant les éléments uniques triés de cet array ainsi que leurs nombres d'occurrence.

import numpy as np

def value_counts(my_array):
    values, counts = np.unique(my_array, return_counts = True)
    return values, counts

values, counts = value_counts(items)

In [16]:
# (o) Afficher le résultat de la fonction appliquée sur items.

print(values)
print(counts)

['Toothbrush' 'air fresher' 'books' 'bowl' 'bread' 'bucket' 'chocolate'
 'clamp' 'crisps' 'flowers' 'football shirt' 'fridge' 'glass' 'glue'
 'hanger' 'headphones' 'jeans' 'knife' 'monitor' 'pencils' 'piano' 'shirt'
 'speakers' 'vase' 'vegetables']
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [17]:
# (p) En vous aidant du tableau promotions, déterminer et afficher le nouveau chiffre d’affaires réalisé par le magasin.
promotions = np.array([0.75,0.75,1,0.5,1,0.9,0.8,0.75,1,1,1,1,0.6,0.7,0.5,
                       0.8,1,1,1,1,0.9,0.75,1,1,1])

new_ca_per_product = quantities * unit_price * promotions
print(new_ca_per_product.sum())

147632.5
